# -*- Controls -*-

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# so i can scroll up to see history
set -g mouse on

# -*- Themeing -*-
# NOTE: using the following tokyonight palette:
#  [lospec](https://lospec.com/palette-list/tokyo-night)

# session windows start at 1
set -g base-index 1

# status bar base colors
set-option -g status-style bg=#1a1b26,fg=#a9b1d6

# session name color and style (and increase separation to window names)
# the '=8:' part truncates session names larger than 8 characters
set-option -g status-left "#[fg=#1f2335,bg=#7aa2f7,bold] #{=8:#{session_name}} "

# window name colors and styles (orange is the selected one)
set-window-option -g window-status-format "#[fg=#a9b1d6,bg=#1f2335] #I #W "
set-window-option -g window-status-current-format "#[fg=#ff9e64,bg=#1f2335] #I #W "

# activity/bells are yellow/red
set-window-option -g window-status-activity-style fg=#ffc777
set-window-option -g window-status-bell-style fg=#c53b53

# status bar right-side content, colors and styles
set-option -g status-right " #[fg=#a9b1d6,bg=#1f2335] %a %d %b %H:%M #[fg=#1f2335,bg=#7aa2f7,bold] #H"

# set the window list separator
set-option -g window-status-separator ""
